# Generated by Django 5.0.10 on 2026-03-06 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('companies', '0001_initial'),
        ('documents', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentalert',
            name='driver_license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='documents.driverlicense'),
        ),
        migrations.AddField(
            model_name='documentalert',
            name='vehicle_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='documents.vehicledocument'),
        ),
        migrations.AddField(
            model_name='maintenancealert',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_alerts', to='companies.company'),
        ),
        migrations.AddField(
            model_name='maintenancealert',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_alerts', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='notification',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='companies.company'),
        ),
        migrations.AddField(
            model_name='notification',
            name='document_alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='alerts.documentalert'),
        ),
        migrations.AddField(
            model_name='notification',
            name='maintenance_alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='alerts.maintenancealert'),
        ),
        migrations.AddIndex(
            model_name='documentalert',
            index=models.Index(fields=['company', 'state', 'scheduled_for'], name='alerts_docu_company_50b978_idx'),
        ),
        migrations.AddIndex(
            model_name='documentalert',
            index=models.Index(fields=['company', 'due_date'], name='alerts_docu_company_f112f0_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancealert',
            index=models.Index(fields=['company', 'state'], name='alerts_main_company_804e6c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['company', 'status', 'available_at'], name='alerts_noti_company_386707_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'attempts'], name='alerts_noti_status_02c546_idx'),
        ),
    ]
