# Generated by Django 5.0.10 on 2026-03-06 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=16)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['job_name', 'created_at'], name='alerts_jobr_job_nam_edfeac_idx'), models.Index(fields=['status', 'created_at'], name='alerts_jobr_status_99ae57_idx')],
            },
        ),
    ]
