# Generated by Codex on 2026-03-20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("alerts", "0003_jobrun"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="PushDevice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(blank=True, default="", max_length=64)),
                ("provider", models.CharField(choices=[("web", "Web"), ("fcm", "Firebase / FCM")], default="web", max_length=16)),
                ("token", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("last_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="push_devices", to="companies.company")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="push_devices", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("company", "token"), name="uniq_push_device_company_token"),
                ],
                "indexes": [
                    models.Index(fields=["company", "user", "is_active"], name="alerts_push_company_6d45cb_idx"),
                    models.Index(fields=["company", "provider", "is_active"], name="alerts_push_company_b265d5_idx"),
                ],
            },
        ),
    ]
