# Generated by Codex on 2026-03-21

import django.db.models.deletion
from django.db import migrations, models


def backfill_maintenance_record_fk(apps, schema_editor):
    MaintenanceAlert = apps.get_model("alerts", "MaintenanceAlert")
    MaintenanceRecord = apps.get_model("maintenance", "MaintenanceRecord")

    alerts = MaintenanceAlert.objects.filter(
        maintenance_record__isnull=True,
    ).exclude(maintenance_record_ref="")

    for alert in alerts.iterator(chunk_size=500):
        try:
            record_id = int(alert.maintenance_record_ref)
        except (TypeError, ValueError):
            continue

        record = MaintenanceRecord.objects.filter(
            id=record_id,
            company_id=alert.company_id,
            vehicle_id=alert.vehicle_id,
        ).first()
        if record is not None:
            MaintenanceAlert.objects.filter(id=alert.id).update(maintenance_record_id=record.id)


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0001_initial"),
        ("alerts", "0004_notification_payload_pushdevice"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancealert",
            name="maintenance_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maintenance_alerts",
                to="maintenance.maintenancerecord",
            ),
        ),
        migrations.RunPython(backfill_maintenance_record_fk, migrations.RunPython.noop),
    ]
