# Generated by Django 5.0.10 on 2026-03-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_maintenancealert_record_fk'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pushdevice',
            new_name='alerts_push_company_86ca8b_idx',
            old_name='alerts_push_company_6d45cb_idx',
        ),
        migrations.RenameIndex(
            model_name='pushdevice',
            new_name='alerts_push_company_a8ffed_idx',
            old_name='alerts_push_company_b265d5_idx',
        ),
        migrations.AlterField(
            model_name='documentalert',
            name='kind',
            field=models.CharField(choices=[('expiry', 'Expiry'), ('expired', 'Expired')], default='expiry', max_length=32),
        ),
        migrations.AlterField(
            model_name='maintenancealert',
            name='kind',
            field=models.CharField(choices=[('by_date', 'By date'), ('by_km', 'By km'), ('overdue_date', 'Overdue by date'), ('overdue_km', 'Overdue by km')], max_length=16),
        ),
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('in_app', 'In App'), ('push', 'Push')], max_length=16),
        ),
    ]
