# Generated by Django 5.0.10 on 2026-03-22 03:29

from django.db import migrations, models


def migrate_legacy_push_notifications(apps, schema_editor):
    """Convierte registros históricos push al canal interno antes de retirar ese módulo."""
    Notification = apps.get_model("alerts", "Notification")
    Notification.objects.filter(channel="push").update(channel="in_app")


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_rename_alerts_push_company_6d45cb_idx_alerts_push_company_86ca8b_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_push_notifications, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('in_app', 'In App')], max_length=16),
        ),
        migrations.DeleteModel(
            name='PushDevice',
        ),
    ]
