# Generated by Django 5.0.10 on 2026-03-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_alter_notification_channel_delete_pushdevice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentalert',
            options={'verbose_name': 'alerta documental', 'verbose_name_plural': 'alertas documentales'},
        ),
        migrations.AlterModelOptions(
            name='jobrun',
            options={'verbose_name': 'ejecución de tarea', 'verbose_name_plural': 'ejecuciones de tareas'},
        ),
        migrations.AlterModelOptions(
            name='maintenancealert',
            options={'verbose_name': 'alerta de mantención', 'verbose_name_plural': 'alertas de mantención'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'notificación', 'verbose_name_plural': 'notificaciones'},
        ),
        migrations.AlterField(
            model_name='documentalert',
            name='kind',
            field=models.CharField(choices=[('expiry', 'Por vencer'), ('expired', 'Vencido')], default='expiry', max_length=32),
        ),
        migrations.AlterField(
            model_name='documentalert',
            name='state',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviada'), ('acknowledged', 'Acusada'), ('resolved', 'Resuelta')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='jobrun',
            name='status',
            field=models.CharField(choices=[('success', 'Exitoso'), ('failed', 'Fallido')], default='success', max_length=16),
        ),
        migrations.AlterField(
            model_name='maintenancealert',
            name='kind',
            field=models.CharField(choices=[('by_date', 'Por fecha'), ('by_km', 'Por kilometraje'), ('overdue_date', 'Atrasada por fecha'), ('overdue_km', 'Atrasada por kilometraje')], max_length=16),
        ),
        migrations.AlterField(
            model_name='maintenancealert',
            name='state',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviada'), ('acknowledged', 'Acusada'), ('resolved', 'Resuelta')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('email', 'Correo'), ('in_app', 'Interna')], max_length=16),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('queued', 'En cola'), ('sent', 'Enviada'), ('failed', 'Fallida')], default='queued', max_length=16),
        ),
    ]
