# Generated by Django 5.0.10 on 2026-03-06 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_companylimit'),
        ('documents', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_clp', models.PositiveIntegerField()),
                ('expense_date', models.DateField()),
                ('supplier', models.CharField(blank=True, default='', max_length=255)),
                ('km', models.PositiveIntegerField(default=0)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('approval_status', models.CharField(choices=[('reported', 'Reported'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='reported', max_length=16)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.expensecategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_expenses', to='companies.company')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_expenses', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_expenses', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleExpenseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_links', to='documents.attachment')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_expense_attachments', to='companies.company')),
                ('vehicle_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_links', to='expenses.vehicleexpense')),
            ],
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['company', 'name'], name='expenses_ex_company_39de87_idx'),
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_expense_category_company_name'),
        ),
        migrations.AddIndex(
            model_name='vehicleexpense',
            index=models.Index(fields=['company', 'vehicle', 'expense_date'], name='expenses_ve_company_94292d_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleexpense',
            index=models.Index(fields=['company', 'approval_status', 'payment_status'], name='expenses_ve_company_7a170e_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleexpenseattachment',
            index=models.Index(fields=['company', 'vehicle_expense'], name='expenses_ve_company_8e7b70_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehicleexpenseattachment',
            constraint=models.UniqueConstraint(fields=('vehicle_expense', 'attachment'), name='uniq_vehicle_expense_attachment'),
        ),
    ]
