# Generated by Django 5.0.10 on 2026-03-18 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleexpense',
            options={'verbose_name': 'Gasto de vehículo', 'verbose_name_plural': 'Gastos de vehículo'},
        ),
    ]
