# Generated by Django 5.0.10 on 2026-03-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_vehicleexpense_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'verbose_name': 'categoría de gasto', 'verbose_name_plural': 'categorías de gasto'},
        ),
        migrations.AlterModelOptions(
            name='vehicleexpense',
            options={'verbose_name': 'gasto de vehículo', 'verbose_name_plural': 'gastos de vehículo'},
        ),
        migrations.AlterModelOptions(
            name='vehicleexpenseattachment',
            options={'verbose_name': 'adjunto de gasto', 'verbose_name_plural': 'adjuntos de gasto'},
        ),
        migrations.AlterField(
            model_name='vehicleexpense',
            name='approval_status',
            field=models.CharField(choices=[('reported', 'Reportado'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='reported', max_length=16),
        ),
        migrations.AlterField(
            model_name='vehicleexpense',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Pendiente'), ('paid', 'Pagado')], default='unpaid', max_length=16),
        ),
    ]
