# Generated by Django 5.0.10 on 2026-03-06 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Ej: vehicle.create, expense.approve, document.renew, etc.', max_length=64)),
                ('object_type', models.CharField(help_text='Ej: Vehicle, VehicleDocument, User, etc.', max_length=64)),
                ('object_id', models.CharField(help_text='ID del objeto afectado (string para soportar int/uuid).', max_length=64)),
                ('before_json', models.JSONField(blank=True, null=True)),
                ('after_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, help_text='Puede ser null si la acción es global (superadmin).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='companies.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'created_at'], name='audit_audit_company_35a24b_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_audit_object__1f9df3_idx'), models.Index(fields=['action'], name='audit_audit_action_86e815_idx')],
            },
        ),
    ]
