# Generated by Django 5.0.10 on 2026-03-22 22:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditlog_immutable'),
        ('companies', '0003_alter_branch_options_alter_company_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='metadata_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='remote_addr',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='source',
            field=models.CharField(choices=[('admin', 'Admin'), ('api', 'API'), ('auth', 'Autenticación'), ('system', 'Sistema'), ('notification', 'Notificaciones')], default='system', max_length=24),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='status',
            field=models.CharField(choices=[('success', 'Correcto'), ('failed', 'Fallido'), ('info', 'Informativo'), ('warning', 'Advertencia')], default='info', max_length=24),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['source', 'status', 'created_at'], name='audit_audit_source_b78d9b_idx'),
        ),
    ]
