# Generated by Django 5.0.10 on 2026-03-06 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('preventive', 'Preventive'), ('corrective', 'Corrective')], max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=16)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('service_date', models.DateField()),
                ('odometer_km', models.PositiveIntegerField(default=0)),
                ('cost_clp', models.PositiveIntegerField(default=0)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('next_due_km', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maintenance_records', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='vehicles.vehicle')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'vehicle', 'service_date'], name='maintenance_company_ad2a91_idx'), models.Index(fields=['company', 'status'], name='maintenance_company_aaef8f_idx'), models.Index(fields=['company', 'next_due_date'], name='maintenance_company_a01c66_idx'), models.Index(fields=['company', 'next_due_km'], name='maintenance_company_5b7bda_idx')],
            },
        ),
        migrations.CreateModel(
            name='VehicleOdometerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('expense', 'Expense'), ('maintenance', 'Maintenance')], default='manual', max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odometer_logs', to='companies.company')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_odometer_logs', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odometer_logs', to='vehicles.vehicle')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'vehicle', 'created_at'], name='maintenance_company_c89ee6_idx'), models.Index(fields=['company', 'vehicle', 'km'], name='maintenance_company_68ee3c_idx')],
            },
        ),
    ]
