# Generated by Django 5.0.10 on 2026-03-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancerecord',
            options={'verbose_name': 'mantención', 'verbose_name_plural': 'mantenciones'},
        ),
        migrations.AlterModelOptions(
            name='vehicleodometerlog',
            options={'verbose_name': 'registro de odómetro', 'verbose_name_plural': 'registros de odómetro'},
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='status',
            field=models.CharField(choices=[('open', 'Abierto'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='open', max_length=16),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='type',
            field=models.CharField(choices=[('preventive', 'Preventivo'), ('corrective', 'Correctivo')], max_length=16),
        ),
        migrations.AlterField(
            model_name='vehicleodometerlog',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('expense', 'Gasto'), ('maintenance', 'Mantención')], default='manual', max_length=16),
        ),
    ]
