# Generated by Django 5.0.10 on 2026-03-22 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_driver_proxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capability',
            options={'verbose_name': 'capacidad', 'verbose_name_plural': 'capacidades'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'conductor', 'verbose_name_plural': 'conductores'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'rol', 'verbose_name_plural': 'roles'},
        ),
        migrations.AlterModelOptions(
            name='rolecapability',
            options={'verbose_name': 'capacidad del rol', 'verbose_name_plural': 'capacidades del rol'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': 'rol de usuario', 'verbose_name_plural': 'roles de usuario'},
        ),
    ]
