# Generated by Django 5.0.10 on 2026-03-06 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rut', models.CharField(help_text='RUT de la empresa. Único en el sistema.', max_length=32, unique=True)),
                ('plan', models.CharField(default='trial', help_text='Nombre del plan. Por ahora sirve para límites internos y futura facturación.', max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['rut'], name='companies_c_rut_dfe14e_idx'), models.Index(fields=['status'], name='companies_c_status_2407e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, default='', max_length=512)),
                ('cost_center_code', models.CharField(blank=True, default='', help_text='Código interno del centro de costo (si el cliente lo usa).', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='companies.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'name'], name='companies_b_company_79b11f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_branch_company_name'),
        ),
    ]
