# Generated by Django 5.0.10 on 2026-03-06 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_vehicles', models.PositiveIntegerField(default=100)),
                ('max_users', models.PositiveIntegerField(default=50)),
                ('max_storage_mb', models.PositiveIntegerField(default=1024)),
                ('max_uploads_per_day', models.PositiveIntegerField(default=200)),
                ('max_exports_per_day', models.PositiveIntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='companies.company')),
            ],
        ),
    ]
