# Generated by Django 5.0.10 on 2026-03-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companylimit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'sucursal', 'verbose_name_plural': 'sucursales'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'empresa', 'verbose_name_plural': 'empresas'},
        ),
        migrations.AlterModelOptions(
            name='companylimit',
            options={'verbose_name': 'membresía', 'verbose_name_plural': 'membresías'},
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('active', 'Activa'), ('suspended', 'Suspendida')], default='active', max_length=16),
        ),
    ]
