# Generated by Django 5.0.10 on 2026-03-22 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_branch_options_alter_company_options_and_more'),
        ('vehicles', '0002_alter_vehicle_options_alter_vehicle_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, help_text='Piloto responsable (si aplica).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Conductor asignado'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='companies.branch', verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='companies.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='current_km',
            field=models.PositiveIntegerField(default=0, verbose_name='Kilometraje actual'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_number',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Número de motor'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(help_text='Patente. Única por empresa.', max_length=16, verbose_name='Patente'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=16, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='VIN'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año'),
        ),
    ]
