# Generated by Django 5.0.10 on 2026-03-22 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tagcharge',
            new_name='tags_tagcha_company_0a772a_idx',
            old_name='tags_tagcha_company_63ed9c_idx',
        ),
        migrations.RenameIndex(
            model_name='tagcharge',
            new_name='tags_tagcha_company_6a7e1f_idx',
            old_name='tags_tagcha_company_004aaa_idx',
        ),
        migrations.RenameIndex(
            model_name='tagcharge',
            new_name='tags_tagcha_company_20c2f6_idx',
            old_name='tags_tagcha_company_7bd0cb_idx',
        ),
        migrations.RenameIndex(
            model_name='tagimportbatch',
            new_name='tags_tagimp_company_312b86_idx',
            old_name='tags_tagimp_company_17c9bc_idx',
        ),
        migrations.RenameIndex(
            model_name='tagtransit',
            new_name='tags_tagtra_company_128c99_idx',
            old_name='tags_tagtra_company_1c59f5_idx',
        ),
        migrations.RenameIndex(
            model_name='tagtransit',
            new_name='tags_tagtra_company_64cbb8_idx',
            old_name='tags_tagtra_company_447650_idx',
        ),
        migrations.RenameIndex(
            model_name='tagtransit',
            new_name='tags_tagtra_company_24f79b_idx',
            old_name='tags_tagtra_company_c8b161_idx',
        ),
        migrations.RenameIndex(
            model_name='tollgate',
            new_name='tags_tollga_company_2a34e5_idx',
            old_name='tags_tollga_company_3fd1ab_idx',
        ),
        migrations.RenameIndex(
            model_name='tollgate',
            new_name='tags_tollga_company_0b681a_idx',
            old_name='tags_tollga_company_f0d8b8_idx',
        ),
        migrations.RenameIndex(
            model_name='tollroad',
            new_name='tags_tollro_company_f3c84c_idx',
            old_name='tags_tollro_company_53f6e1_idx',
        ),
    ]
