# Generated by Django 5.0.10 on 2026-03-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_branch_options_alter_company_options_and_more'),
        ('tags', '0002_rename_tags_tagcha_company_63ed9c_idx_tags_tagcha_company_0a772a_idx_and_more'),
        ('vehicles', '0002_alter_vehicle_options_alter_vehicle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagcharge',
            name='invoice_reference',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='tagcharge',
            name='is_weekend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tagcharge',
            name='schedule_code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='tagcharge',
            name='tag_reference',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='tagimportbatch',
            name='total_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tagtransit',
            name='invoice_reference',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='tagtransit',
            name='is_weekend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tagtransit',
            name='schedule_code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='tagtransit',
            name='tag_reference',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='tagcharge',
            index=models.Index(fields=['company', 'is_weekend', 'charge_date'], name='tags_tagcha_company_3e8826_idx'),
        ),
        migrations.AddIndex(
            model_name='tagtransit',
            index=models.Index(fields=['company', 'is_weekend', 'transit_date'], name='tags_tagtra_company_bbd16b_idx'),
        ),
    ]
