# Generated by Django 5.0.10 on 2026-03-06 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key', models.CharField(max_length=512, unique=True)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('mime_type', models.CharField(max_length=128)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=64)),
                ('category', models.CharField(blank=True, default='', max_length=64)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('reminder_days_before', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('replaced', 'Replaced'), ('expired', 'Expired')], default='active', max_length=16)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_licenses', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_driver_licenses', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_licenses', to=settings.AUTH_USER_MODEL)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='documents.driverlicense')),
            ],
        ),
        migrations.CreateModel(
            name='DriverLicenseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_license_links', to='documents.attachment')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_license_attachments', to='companies.company')),
                ('driver_license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_links', to='documents.driverlicense')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('permiso_circulacion', 'Permiso de circulacion'), ('revision_tecnica', 'Revision tecnica'), ('seguro', 'Seguro'), ('otro', 'Otro')], max_length=64)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('reminder_days_before', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('replaced', 'Replaced'), ('expired', 'Expired')], default='active', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_documents', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vehicle_documents', to=settings.AUTH_USER_MODEL)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='documents.vehicledocument')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_document_links', to='documents.attachment')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_document_attachments', to='companies.company')),
                ('vehicle_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_links', to='documents.vehicledocument')),
            ],
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['company', 'created_at'], name='documents_a_company_7ad2fc_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['company', 'mime_type'], name='documents_a_company_c6a37c_idx'),
        ),
        migrations.AddIndex(
            model_name='driverlicense',
            index=models.Index(fields=['company', 'expiry_date'], name='documents_d_company_5630b8_idx'),
        ),
        migrations.AddIndex(
            model_name='driverlicense',
            index=models.Index(fields=['company', 'is_current'], name='documents_d_company_3bc6de_idx'),
        ),
        migrations.AddConstraint(
            model_name='driverlicense',
            constraint=models.UniqueConstraint(fields=('company', 'driver', 'license_number', 'is_current'), name='uniq_driver_license_current'),
        ),
        migrations.AddIndex(
            model_name='driverlicenseattachment',
            index=models.Index(fields=['company', 'driver_license'], name='documents_d_company_a9a77a_idx'),
        ),
        migrations.AddConstraint(
            model_name='driverlicenseattachment',
            constraint=models.UniqueConstraint(fields=('driver_license', 'attachment'), name='uniq_driver_license_attachment'),
        ),
        migrations.AddIndex(
            model_name='vehicledocument',
            index=models.Index(fields=['company', 'vehicle', 'type'], name='documents_v_company_bb0ad1_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicledocument',
            index=models.Index(fields=['company', 'expiry_date'], name='documents_v_company_11ac87_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicledocument',
            index=models.Index(fields=['company', 'is_current'], name='documents_v_company_6e7975_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicledocumentattachment',
            index=models.Index(fields=['company', 'vehicle_document'], name='documents_v_company_20b2e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehicledocumentattachment',
            constraint=models.UniqueConstraint(fields=('vehicle_document', 'attachment'), name='uniq_vehicle_document_attachment'),
        ),
    ]
