# Generated by Django 5.0.10 on 2026-03-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledocument',
            name='type',
            field=models.CharField(choices=[('permiso_circulacion', 'Permiso de circulacion'), ('revision_tecnica', 'Revision tecnica'), ('tecnomecanica', 'Tecnomecanica'), ('seguro', 'SOAP'), ('gases', 'Gases'), ('otro', 'Otro')], max_length=64),
        ),
    ]
