# Generated by Django 5.0.10 on 2026-03-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_vehicledocument_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'adjunto', 'verbose_name_plural': 'adjuntos'},
        ),
        migrations.AlterModelOptions(
            name='driverlicense',
            options={'verbose_name': 'licencia de conducir', 'verbose_name_plural': 'licencias de conducir'},
        ),
        migrations.AlterModelOptions(
            name='driverlicenseattachment',
            options={'verbose_name': 'adjunto de licencia', 'verbose_name_plural': 'adjuntos de licencia'},
        ),
        migrations.AlterModelOptions(
            name='vehicledocument',
            options={'verbose_name': 'documento del vehículo', 'verbose_name_plural': 'documentos del vehículo'},
        ),
        migrations.AlterModelOptions(
            name='vehicledocumentattachment',
            options={'verbose_name': 'adjunto de documento', 'verbose_name_plural': 'adjuntos de documento'},
        ),
        migrations.AlterField(
            model_name='driverlicense',
            name='status',
            field=models.CharField(choices=[('active', 'Activa'), ('replaced', 'Reemplazada'), ('expired', 'Vencida')], default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='vehicledocument',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('replaced', 'Reemplazado'), ('expired', 'Vencido')], default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='vehicledocument',
            name='type',
            field=models.CharField(choices=[('permiso_circulacion', 'Permiso de circulación'), ('revision_tecnica', 'Revisión técnica'), ('tecnomecanica', 'Tecnomecánica'), ('seguro', 'SOAP'), ('gases', 'Gases'), ('otro', 'Otro')], max_length=64),
        ),
    ]
