# Generated by Django 5.0.10 on 2026-03-06 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=64)),
                ('export_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'XLSX')], default='csv', max_length=8)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('rejected', 'Rejected')], default='completed', max_length=16)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_export_logs', to='companies.company')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_export_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'created_at'], name='reports_rep_company_94499a_idx'), models.Index(fields=['company', 'report_type', 'created_at'], name='reports_rep_company_74155f_idx')],
            },
        ),
    ]
