# Generated by Django 5.0.10 on 2026-03-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportexportlog',
            name='export_format',
            field=models.CharField(choices=[('csv', 'CSV'), ('pdf', 'PDF'), ('xlsx', 'XLSX')], default='csv', max_length=8),
        ),
    ]
