# Generated by Django 5.0.10 on 2026-03-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_reportexportlog_export_format'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportexportlog',
            options={'verbose_name': 'exportación de reporte', 'verbose_name_plural': 'exportaciones de reportes'},
        ),
        migrations.AlterField(
            model_name='reportexportlog',
            name='status',
            field=models.CharField(choices=[('completed', 'Completado'), ('rejected', 'Rechazado')], default='completed', max_length=16),
        ),
    ]
